var categoryNames = [["原核", "原生", "真菌","蘚苔", "蕨類", "裸子植物", "單子葉植物","雙子葉植物"]];
var cardData = [
	{"name":"藍綠菌","category":"原核"},
	{"name":"藍綠藻","category":"原核"},
	{"name":"藍菌","category":"原核"},
	{"name":"細菌","category":"原核"},
	{"name":"金黃色葡萄球菌","category":"原核"},
	{"name":"結核桿菌","category":"原核"},
	{"name":"鉤端螺旋體菌","category":"原核"},
	{"name":"瘤胃球菌","category":"原核"},
	{"name":"乳酸菌","category":"原核"},
	{"name":"色球藻","category":"原核"},
	{"name":"顫藻","category":"原核"},
	{"name":"念珠藻","category":"原核"},
	{"name":"雨來菇","category":"原核"},
	{"name":"原核生物","category":"原核"},
	{"name":"單胞藻","category":"原生"},
	{"name":"眼蟲","category":"原生"},
	{"name":"裸藻","category":"原生"},
	{"name":"石蓴","category":"原生"},
	{"name":"昆布","category":"原生"},
	{"name":"海帶","category":"原生"},
	{"name":"矽藻","category":"原生"},
	{"name":"巨藻","category":"原生"},
	{"name":"石花菜","category":"原生"},
	{"name":"草履蟲","category":"原生"},
	{"name":"線鞭蟲","category":"原生"},
	{"name":"瘧原蟲","category":"原生"},
	{"name":"變形蟲","category":"原生"},
	{"name":"黏菌","category":"原生"},
	{"name":"原生菌","category":"原生"},
	{"name":"原生動物","category":"原生"},
	{"name":"真菌","category":"真菌"},
	{"name":"酵母菌","category":"真菌"},
	{"name":"黴菌","category":"真菌"},
	{"name":"足癬","category":"真菌"},
	{"name":"黑黴菌","category":"真菌"},
	{"name":"青黴菌","category":"真菌"},
	{"name":"蕈類","category":"真菌"},
	{"name":"木耳","category":"真菌"},
	{"name":"竹蓀","category":"真菌"},
	{"name":"靈芝","category":"真菌"},
	{"name":"毒蠅傘","category":"真菌"},
	{"name":"毒瓢蕈","category":"真菌"},
	{"name":"香菇","category":"真菌"},
	{"name":"蟲草菌","category":"真菌"},
  { name: "蘚苔", category: "蘚苔" },
  { name: "土馬騌", category: "蘚苔" },
  { name: "水苔", category: "蘚苔" },
  { name: "地錢", category: "蘚苔" },
  { name: "鐵線蕨", category: "蕨類" },
  { name: "鳥巢蕨", category: "蕨類" },
  { name: "過貓", category: "蕨類" },
  { name: "腎蕨", category: "蕨類" },
  { name: "矮松", category: "裸子植物" },
  { name: "二葉松", category: "裸子植物" },
  { name: "歐洲赤松", category: "裸子植物" },
  { name: "剛葉松", category: "裸子植物" },
  { name: "銀杏", category: "裸子植物" },
  { name: "蘇鐵", category: "裸子植物" },
  { name: "紅檜", category: "裸子植物" },
  { name: "松樹", category: "裸子植物" },
  { name: "綠豆", category: "雙子葉植物" },  
  { name: "花生", category: "雙子葉植物" },
  { name: "豌豆", category: "雙子葉植物" },
  { name: "向日葵", category: "雙子葉植物" },
  { name: "菩提", category: "雙子葉植物" },
  { name: "油菜", category: "雙子葉植物" },
  { name: "油桐", category: "雙子葉植物" },
  { name: "櫻花", category: "雙子葉植物" },
  { name: "橘子", category: "雙子葉植物" },
  { name: "榕樹", category: "雙子葉植物" },  
  { name: "臺灣百合", category: "單子葉植物" },
  { name: "竹子", category: "單子葉植物" },
  { name: "玉米", category: "單子葉植物" },
  { name: "蔥", category: "單子葉植物" },
  { name: "紫錦草", category: "單子葉植物" },
  { name: "稻", category: "單子葉植物" },
  { name: "蘭花", category: "單子葉植物" },
  { name: "水仙", category: "單子葉植物" },	
  { name: "登革熱", category: "病毒" },	  
  { name: "新冠肺炎", category: "病毒" },	    
{ name: "小兒麻痺", category: "病毒" },
{ name: "日本腦炎", category: "病毒" },
{ name: "麻疹", category: "病毒" },
{ name: "水痘", category: "病毒" },
{ name: "病毒", category: "病毒" },
{ name: "愛滋病", category: "病毒" },
{ name: "肺結核", category: "原核" },
{ name: "傷寒", category: "原核" },
{ name: "霍亂", category: "原核" },
{ name: "球菌", category: "原核" },
];
