var categoryNames = [
  ["刺絲胞", "扁形", "軟體", "環節"],
  ["節肢", "棘皮", "脊索"],
];
var cardData = [
  { name: "水母", category: "刺絲胞動物" },
  { name: "水螅", category: "刺絲胞動物" },
  { name: "珊瑚", category: "刺絲胞動物" },
  { name: "海葵", category: "刺絲胞動物" },
  { name: "絛蟲", category: "扁形動物" },
  { name: "吸蟲", category: "扁形動物" },
  { name: "肝吸蟲", category: "扁形動物" },
  { name: "渦蟲", category: "扁形動物" },
  { name: "蝸牛", category: "軟體動物" },
  { name: "文蛤", category: "軟體動物" },
  { name: "章魚", category: "軟體動物" },
  { name: "烏賊", category: "軟體動物" },
  { name: "蚯蚓", category: "環節動物" },
  { name: "水蛭", category: "環節動物" },
  { name: "蛭", category: "環節動物" },
  { name: "沙蠶", category: "環節動物" },
  { name: "昆蟲", category: "節肢動物" },
  { name: "蜘蛛", category: "節肢動物" },
  { name: "蝦", category: "節肢動物" },
  { name: "蟹", category: "節肢動物" },
  { name: "蟬", category: "節肢動物" },
  { name: "衣魚", category: "節肢動物" },
  { name: "蟑螂", category: "節肢動物" },
  { name: "螞蟻", category: "節肢動物" },
  { name: "海星", category: "棘皮動物" },
  { name: "海膽", category: "棘皮動物" },
  { name: "海參", category: "棘皮動物" },
  { name: "海膽", category: "棘皮動物" },
  { name: "魟魚", category: "魚類" },
  { name: "鯊魚", category: "魚類" },
  { name: "小丑魚", category: "魚類" },
  { name: "海馬", category: "魚類" },
  { name: "吳郭魚", category: "魚類" },
  { name: "鯉魚", category: "魚類" },
  { name: "蟾蜍", category: "兩生類" },
  { name: "山椒魚", category: "兩生類" },
  { name: "蠑螈", category: "兩生類" },
  { name: "蝌蚪", category: "兩生類" },
  { name: "赤蛙", category: "兩生類" },
  { name: "箭毒蛙", category: "兩生類" }, 
  { name: "海龜", category: "爬蟲類" },  
  { name: "蛇", category: "爬蟲類" },
  { name: "攀蜥", category: "爬蟲類" },
  { name: "鱷", category: "爬蟲類" },
  { name: "斑龜", category: "爬蟲類" },
  { name: "蜥蜴", category: "爬蟲類" },
  { name: "小白鷺", category: "鳥類" },
  { name: "臺灣藍鵲", category: "鳥類" },
  { name: "五色鳥", category: "鳥類" },
  { name: "企鵝", category: "鳥類" },
  { name: "象", category: "哺乳類" },
  { name: "蝙蝠", category: "哺乳類" },
  { name: "鴨嘴獸", category: "哺乳類" },
  { name: "針鼴", category: "哺乳類" },
  { name: "袋鼠", category: "哺乳類" },
  { name: "無尾熊", category: "哺乳類" },
  { name: "虎鯨", category: "哺乳類" },
  { name: "人", category: "哺乳類" },
];
