// 可使用多列答案框
var categoryNames = [
  ["刺絲胞", "扁形", "軟體", "環節"],
  ["節肢", "棘皮", "脊索"],
];
var cardData = [
  { name: "水母", img: "images/1.jpg", category: "刺絲胞" },
  { name: "珊瑚", img: "images/2.jpg", category: "刺絲胞" },
  { name: "水螅", img: "images/3.jpg", category: "刺絲胞" },
  { name: "海葵", img: "images/4.jpg", category: "刺絲胞" },
  { name: "絛蟲", img: "images/5.jpg", category: "扁形" },
  { name: "渦蟲", img: "images/6.jpg", category: "扁形" },
  { name: "絛蟲", img: "images/7.jpg", category: "扁形" },
  { name: "蝸牛", img: "images/8.jpg", category: "軟體" },
  { name: "蛞蝓", img: "images/9.jpg", category: "軟體" },
  { name: "文蛤", img: "images/10.jpg", category: "軟體" },
  { name: "章魚", img: "images/11.jpg", category: "軟體" },
  { name: "烏賊", img: "images/12.jpg", category: "軟體" },
  { name: "蚯蚓", img: "images/13.jpg", category: "環節" },
  { name: "水蛭", img: "images/14.jpg", category: "環節" },
  { name: "沙蠶", img: "images/15.jpg", category: "環節" },
  { name: "水蛭", img: "images/16.jpg", category: "環節" },
  { name: "蜈蚣", img: "images/17.jpg", category: "節肢" },
  { name: "蝴蝶", img: "images/18.jpg", category: "節肢" },
  { name: "螃蟹", img: "images/19.jpg", category: "節肢" },
  { name: "蜘蛛", img: "images/20.jpg", category: "節肢" },
  { name: "蝦", img: "images/21.jpg", category: "節肢" },
  { name: "蒼蠅", img: "images/22.jpg", category: "節肢" },
  { name: "海星", img: "images/23.jpg", category: "棘皮" },
  { name: "海蛇尾", img: "images/24.jpg", category: "棘皮" },
  { name: "海膽", img: "images/25.jpg", category: "棘皮" },
  { name: "海參", img: "images/26.jpg", category: "棘皮" },
  { name: "海參", img: "images/27.jpg", category: "棘皮" },
  { name: "鯊魚", img: "images/28.jpg", category: "脊索" },
  { name: "魚", img: "images/29.jpg", category: "脊索" },
  { name: "青蛙", img: "images/30.jpg", category: "脊索" },
  { name: "蠑螈", img: "images/31.jpg", category: "脊索" },
  { name: "蜥蜴", img: "images/32.jpg", category: "脊索" },
  { name: "蛇", img: "images/33.jpg", category: "脊索" },
  { name: "龜", img: "images/34.jpg", category: "脊索" },
  { name: "企鵝", img: "images/35.jpg", category: "脊索" },
  { name: "穿山甲", img: "images/36.jpg", category: "脊索" },
];
