var categoryNames = [["魚類", "兩生類", "爬蟲類", "鳥類", "哺乳類"]];
var cardData = [
  { name: "魟魚", category: "魚類" },
  { name: "鯊魚", category: "魚類" },
  { name: "小丑魚", category: "魚類" },
  { name: "海馬", category: "魚類" },
  { name: "吳郭魚", category: "魚類" },
  { name: "鯉魚", category: "魚類" },
  { name: "蟾蜍", category: "兩生類" },
  { name: "山椒魚", category: "兩生類" },
  { name: "蠑螈", category: "兩生類" },
  { name: "蝌蚪", category: "兩生類" },
  { name: "赤蛙", category: "兩生類" },
  { name: "青蛙", category: "兩生類" },
  { name: "壁虎", category: "爬蟲類" },
  { name: "蛇", category: "爬蟲類" },
  { name: "攀蜥", category: "爬蟲類" },
  { name: "短吻鱷", category: "爬蟲類" },
  { name: "斑龜", category: "爬蟲類" },
  { name: "蜥蜴", category: "爬蟲類" },
  { name: "小白鷺", category: "鳥類" },
  { name: "臺灣藍鵲", category: "鳥類" },
  { name: "五色鳥", category: "鳥類" },
  { name: "企鵝", category: "鳥類" },
  { name: "象", category: "哺乳類" },
  { name: "蝙蝠", category: "哺乳類" },
  { name: "鴨嘴獸", category: "哺乳類" },
  { name: "針鼴", category: "哺乳類" },
  { name: "袋鼠", category: "哺乳類" },
  { name: "無尾熊", category: "哺乳類" },
  { name: "虎鯨", category: "哺乳類" },
  { name: "人", category: "哺乳類" },
];
