var categoryNames = [
  ["刺絲胞動物", "扁形動物", "軟體動物"],
  ["環節動物", "節肢動物", "棘皮動物"],
];
var cardData = [
  { name: "水母", category: "刺絲胞動物" },
  { name: "水螅", category: "刺絲胞動物" },
  { name: "珊瑚", category: "刺絲胞動物" },
  { name: "海葵", category: "刺絲胞動物" },
  { name: "絛蟲", category: "扁形動物" },
  { name: "吸蟲", category: "扁形動物" },
  { name: "肝吸蟲", category: "扁形動物" },
  { name: "渦蟲", category: "扁形動物" },
  { name: "蝸牛", category: "軟體動物" },
  { name: "文蛤", category: "軟體動物" },
  { name: "章魚", category: "軟體動物" },
  { name: "烏賊", category: "軟體動物" },
  { name: "蚯蚓", category: "環節動物" },
  { name: "水蛭", category: "環節動物" },
  { name: "蛭", category: "環節動物" },
  { name: "沙蠶", category: "環節動物" },
  { name: "昆蟲", category: "節肢動物" },
  { name: "蜘蛛", category: "節肢動物" },
  { name: "蝦", category: "節肢動物" },
  { name: "蟹", category: "節肢動物" },
  { name: "蟬", category: "節肢動物" },
  { name: "衣魚", category: "節肢動物" },
  { name: "蟑螂", category: "節肢動物" },
  { name: "螞蟻", category: "節肢動物" },
  { name: "海星", category: "棘皮動物" },
  { name: "海膽", category: "棘皮動物" },
  { name: "海參", category: "棘皮動物" },
  { name: "海膽", category: "棘皮動物" },
];
