name: Deploy bioannotator

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build bioannotator_src
        run: |
          cd bioannotator_src
          npm ci
          npm run build

      - name: Deploy to bioannotator directory
        run: |
          # Clean all conflicting paths from Git index (case-insensitive)
          git ls-files | grep -i '^bioannotator/' | xargs -r git rm --cached
          rm -rf bioannotator

          # Copy new build
          mkdir -p bioannotator
          cp -r bioannotator_src/dist/* bioannotator/

          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add, commit, push if changed
          git add -f bioannotator
          if git diff --staged --quiet; then
            echo "No changes to deploy."
          else
            git commit -m "Deploy: Update bioannotator subproject"
            git push
          fi
